### ISSUE TITLE
Centre aligned text remains in place on resize

### ISSUE THREAD

**Issue by davwheat** [akzhy/Vara#17]
This library is amazing. I mean... amazing.

---

When I draw text with `textAlign: "center"`, it gets centred beautifully, but doesn't remain centred on a window resize. Is there any way to keep it centred/recalculate position on resize?

**Comment by akzhy** [comment]
Hi,
Thanks, currently the library doesn't redraw on screen size. This is because manipulating and redrawing SVG can be expensive, memory-wise.
However, I am rebuilding the library to make it much more efficient and modular. The feature will be added once I complete the new version.
With the current code structure, the only way to implement a redraw method will be to delete the innerHTML of the container element and then recalling `Vara`, but this can cause memory issues.

**Comment by davwheat** [comment]
That's what I've just implemented right now using a passive resize event
listener.

**Comment by akzhy** [comment]
Great 👍 will add the feature in the new version.
